blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("posts.urls", namespace='posts'),),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import(
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
    category,
)
urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^category/(?P<id>[0-9]{1})/$', category, name='category'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w\-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w\-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w\-]+)/delete/$', post_delete, name='delete'),
]

posts/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.text import slugify
# Create your models here.

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    return "%s/%s" %(instance.id, filename)

class UserImage(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    foto = models.ImageField(upload_to=upload_location,
            null=True, blank=True,
            width_field="width_field",
            height_field="height_field")
    width_field = models.IntegerField(default=0)
    height_field = models.IntegerField(default=0)
    about = models.TextField()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

class CategoryPost(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

class Message(models.Model):
    name = models.CharField(max_length=256)
    email = models.EmailField(max_length=254)
    content = models.TextField()
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, allow_unicode=True)
    image = models.ImageField(upload_to=upload_location,
            null=True, blank=True,
            width_field="width_field",
            height_field="height_field")
    width_field = models.IntegerField(default=0)
    height_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    category = models.ForeignKey(CategoryPost)
    objects = PostManager()
 
    def __unicode__(self):
        return self.title
    
    def __str__(self):
        return self.title
   
    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})
        #return "/posts/%s/" %(self.id)
    
    class Meta:
        ordering = ["-timestamp", "-updated"]
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

def create_slug(instance, new_slug=None):
    slug = slugify(instance.slug)
    if new_slug is not None:
        slug  = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title', 
            'slug',
            'image',
            'content',
            'draft',
            'publish',
            'category',
        ]

posts/views.py
from urllib.parse import quote_plus
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import PostForm
from .models import Post, UserImage, CategoryPost, Message
# Create your views here.

def category(request, id):
    category = CategoryPost.objects.get(id=id)
    queryset_list = Post.objects.filter(category=category)
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
                            Q(title__icontains=query) |
                            Q(content__icontains=query) |
                            Q(user__first_name__icontains=query) |
                            Q(user__last_name__icontains=query)).distinct()
    paginator = Paginator(queryset_list, 9) # Show 25 contacts per page
    page_request_var = 'page' 
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
        "object_list": queryset,
        "page_request_var": page_request_var,
        "category": category,
    }
    return render(request, 'category.html', context)

def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, 'Successfuly Created')
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'form': form,
    }
    return render(request, 'post_form.html', context)   

def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None,request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
    }
    return render(request, 'post_form.html', context)

def post_list(request):
    today = timezone.now().date()
    admin_list = UserImage.objects.all()
    queryset_list = Post.objects.active() #order_by('-timestamp')
    if request.method == "POST":   
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        message = Message.objects.create(name=name, email=email, content=message)
        message.save()
        return HttpResponseRedirect(
                        u'%s?status_message=Сообщение отправлено!' %
                        reverse('posts:list'))
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
                            Q(title__icontains=query) |
                            Q(content__icontains=query) |
                            Q(user__first_name__icontains=query) |
                            Q(user__last_name__icontains=query)).distinct()
    paginator = Paginator(queryset_list, 6) # Show 25 contacts per page
    page_request_var = 'page' 
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
        "object_list": queryset,
        "page_request_var": page_request_var,
        "today": today, 
        "admin_list": admin_list,
    }
    return render(request, 'post_list_new.html', context)





def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    context = {
        "title": instance.title,
        "instance": instance,
        "share_string": share_string,
    }
    return render(request, 'post_detail.html', context)

def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, 'Successfuly deleted')
    return redirect("post:list")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block head_title %} Блог{% endblock head_title %}</title>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="Vegan" name="description">
    
    <!--styles -->

    <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">
    <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


    <link id="ct-chosen-google-fonts-css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Playfair+Display%3A400%7CRaleway%3A400%2C700%2C400italic&subset=latin%2Clatin-ext&ver=4.8" type="text/css" media="all"> 
    
    
    <!--fonts google-->
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,700' rel='stylesheet' type='text/css'>
    

  </head>
  <body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
{% include "preloader.html" %}
{% include "header_new.html" %}
{% block content%}{% endblock content%}


    
    

    <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
            crossorigin="anonymous"></script>   
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{% static 'js/classie.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/masonry.pkgd.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/masonry.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/smooth-scroll.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/typed.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/main.js' %}" type="text/javascript"></script>
  </body>
</html>

templates/category.html
{% extends "base.html" %}
{% load staticfiles%}
{% block content%}
<!--CONTENT WRAP-->
<div class="content-wrap">
      <!--CONTENT-->
    <div class="content">
<!--BLOG-->
<section class="grey-bg" id="blog">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="title-small-center text-center">
                    <span>{{category.name}}</span>
                </h3>
                <div class="row">
                    <form method="GET" action="">
                        <div class="col-md-4 search">
                             <div class="input-group">
                                <input class="form-control" type="text" placeholder="Найти статью..." title="Поиск" name="q" value="{{ request.GET.q }}">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                </span>
                            </div><!-- /input-group -->
                        </div><!-- /.col-md-4 -->
                    </form>
                </div>
                <div class="col-md-12 content-right">
                    <div class="row">
                        <ul class="listing-item">
                            {% for obj in object_list %}
                            <li>
                                <div class="col-md-4 col-sm-6">
                                    <div class="wrap-card">
                                        <div class="card">
                                            {% if obj.image %} 
                                            <img alt="blog-1" class="img-circle" width="133" height="133" src="{{obj.image.url}}">
                                            {% endif %}
                                            <p class="subtitle fancy">
                                                <span>{{obj.publish}}</span>
                                            </p>
                                            <a href="{{obj.get_absolute_url}}">
                                                <h2 class="title">{{obj.title}}</h2>
                                            </a>
                                            <div class="text-detail">
                                                <p>{{obj.content|linebreaks|truncatechars:120}}<a href="{{obj.get_absolute_url}}" class="green">Читать далее &rarr;</a></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- Pagination  -->
    <div class="row">
        <div class="col-md-3 col-md-offset-5">
            <div class="pagination">
                <span class="step-links">
                    {% if object_list.has_previous %}
                    <a href="?{{page_request_var}}={{ object_list.previous_page_number }}{% if request.GET.q%}&q={{ request.GET.q}}{% endif %}" class="next">&larr;</a>
                    {% endif %}
                    <span class="current">Страница {{ object_list.number }} с {{ object_list.paginator.num_pages }}.</span>
                    {% if object_list.has_next %}
                    <a href="?{{page_request_var}}={{ object_list.next_page_number }}{% if request.GET.q%}&q={{ request.GET.q}}{% endif %}" class="next">&rarr;</a>
                    {% endif %}
                </span>
            </div>
        </div>  
    </div> 
</section>
<!--/.BLOG END-->
{% include "footer.html" %}
<!--/.CONTENT END-->
    </div>
    <!--/.CONTENT-WRAP END-->
</div>
{% endblock content%}

templates/footer.html
{% load staticfiles %} 

<!--FOOTER-->
        <footer>
          <div class="footer-bottom">
            <div class="container">
              <div class="row">
                <img src="{% static 'images/vegan.png'%}" alt="logo bottom" class="center-block" />
              </div>
            </div>
          </div>
        </footer>

templates/header_new.html
{% load staticfiles %}  
    <!--HEADER -->
    <div class="header">
      <div class="for-sticky">
        <!--LOGO-->
        <div class="col-md-2 col-xs-6 logo">
          <a href="{% url 'posts:list' %}"><img alt="logo" class="logo-nav" src="{% static 'images/vegan.png' %}"></a>
        </div>
        <!--/.LOGO END-->
      </div>
      <div class="menu-wrap" id="menu">
        <nav class="menu">
          <div class="menu-list">
            <a  href="{% url 'posts:list' %}">
              <span>Главная</span>
            </a>
            <a class="exit" href="{% url 'posts:list' %}#about">
              <span>Об авторе</span>
            </a>
            <a  href="{% url 'posts:category' id=3 %}">
              <span>Веганство и сыроедение</span>
            </a><br>
            <a  href="{% url 'posts:category' id=1 %}">
              <span>Рецепты</span>
            </a>
            <a   href="{% url 'posts:category' id=2 %}">
              <span>Полезные советы</span>
            </a>
            <a class="exit" href="{% url 'posts:list' %}#blog">
              <span>Все статьи</span>
            </a>
            <a class="exit" href="{% url 'posts:list' %}#contact">
              <span>Контакты</span>
            </a>

          </div>
        </nav>
        <button class="close-button" id="close-button">Закрыть меню</button>
      </div>
      <button class="menu-button" id="open-button">
        <span></span>
        <span></span>
        <span></span>
      </button><!--/.for-sticky-->
    </div>
    <!--/.HEADER END сделано-->

templates/messages_display.html
{% if messages %}
<div>
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{message}}{% endif %}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}

{% block head_title %} 
{{instance.title}} | {{block.super}}
{% endblock head_title %}

{% block content%}
<!--CONTENT WRAP-->
<div class="content-wrap">
      <!--CONTENT-->
    <div class="content">
        <!--HOME-->
        <section class="grey-bg" id="blog">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h3 style="color: green;"><a href="{% url 'posts:list' %}"> Главная </a><span>>> </span><a href="{% url 'posts:category' id=instance.category.id %}">{{instance.category}}</a></h3>
                    </div>
                    <div class="col-md-8 col-md-offset-2">

                        <h2 class="title-small-center text-center">
                            <span> {{title}} </span>
                        </h2>
                        {% if instance.image %}
                        <img src="{{instance.image.url}}" class="img-responsive text-center">
                        {% endif %}
                        <h2><small>{% if instance.draft %} <span class="red">Черновик</span>{% endif %}{{instance.publish}}</small></h2>
                        <p>
                            <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="standard" data-action="like" data-show-faces="" data-share="true"></div>
                        <hr/>
                        </p>
                        <p>{{instance.content|linebreaks}}<br/></p>
                        <hr/>
                        <div class='col-sm-8 col-sm-offset-2'>
                            <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
                        </div>
                    </div>
                </div>
            </div>
        </section> 
<!--
<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
Facebook
</a>

<a href="https://twitter.com/home?status={{ instance.content|truncatechars:80|urlify }}%20{{ request.build_absolute_uri }}">
Twitter
</a>


<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}">
Linkedin
</a>
-->
{% include "footer.html" %}
<!--/.CONTENT END-->
    </div>
    <!--/.CONTENT-WRAP END-->
</div>
{% endblock content%}

templates/post_form.html
{% extends "base.html" %}
{% block content%}
<div class="col-sm-6 col-sm-offset-3">
    <h1>Form</h1>
    <form method="POST" action="" enctype="multipart/form-data">{% csrf_token%}
    {{form.as_p}}
    <input type="submit" class="btn btn-default" value="Create Post">
    </form>
</div>
{% endblock content%}

templates/post_list_new.html
{% extends "base.html" %}
{% load staticfiles%}
{% block content%}
<!--CONTENT WRAP-->
    <div class="content-wrap">
      <!--CONTENT-->
      <div class="content">
        <!--HOME-->
        
        <section id="home">
          <div class="container">
            <div class="row">
              <div class="wrap-hero-content">
                  <div class="hero-content">
                    <h1>Привет!</h1>
                    <br>
                    <span class="typed"></span>
                  </div>
              </div>
              <div class="mouse-icon margin-20">
                <div class="scroll"></div>
              </div>
            </div>
          </div>
        </section>
        <!--/.HOME END-->

        <!--ABOUT-->
        <section id="about">
          <div class="col-md-4 col-xs-12 no-pad">
            <div class="bg-about"></div>
          </div>
          <div class="col-md-8 col-sm-12 col-xs-12 white-col">
            <div class="row">
                <div class="col-md-12">
                      {% if admin_list %}
                        {% for item in admin_list %}
                      <img src="{{ item.foto.url }}" class="img-thumbnail"  width="140" height="140">
                        {% if item.user.get_full_name %}
                      <h3 class="name">{{item.user.get_full_name}}</h3>
                        {% endif %}
                      </h3>
                      <p class="head-about">
                        {{item.about|linebreaks }}
                      </p>
                        {% endfor %} 
                      {% endif %}

                </div>              
              </div>
          </div>
        </section>
        <!--/.ABOUT END-->

          <!--BLOG-->

        <section class="grey-bg" id="blog">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <h3 class="title-small-center text-center">
                  <span>Последние статьи</span>
                </h3>
                <div class="row">
<form method="GET" action="">
<div class="col-md-4 search">
    <div class="input-group">
<input class="form-control" type="text" placeholder="Найти статью..." title="Поиск" name="q" value="{{ request.GET.q }}">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</form>

                </div>
              <div class="col-md-12 content-right">
                <div class="row">
                  <ul class="listing-item">
                  {% for obj in object_list %}
                    <li>
                      <div class="col-md-4 col-sm-6">
                        <div class="wrap-card">
                          <div class="card">
                            {% if obj.image %} 
                            <img alt="blog-1" class="img-circle" width="133" height="133" src="{{obj.image.url}}">
                            {% endif %}
                      <p class="subtitle fancy">
                        <span>{{obj.publish}}</span>
                      </p>

                      <a href="{{obj.get_absolute_url}}">
                        <h2 class="title">
                          {{obj.title}}
                        </h2>
                      </a>
                            <div class="text-detail">
                              <p>
                                {{obj.content|linebreaks|truncatechars:120}}<a href="{{obj.get_absolute_url}}" class="green">Читать далее &rarr;</a>
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </li>
                 {% endfor %}
                  </ul>
                </div>
              </div>

              </div>
            </div>
          </div>
<!-- Pagination  -->
<div class="row">
<div class="col-md-3 col-md-offset-5">
<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{page_request_var}}={{ object_list.previous_page_number }}{% if request.GET.q%}&q={{ request.GET.q}}{% endif %}" class="next">&larr; Назад</a>
        {% endif %}

        <span class="current">
            Страница {{ object_list.number }} из {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{page_request_var}}={{ object_list.next_page_number }}{% if request.GET.q%}&q={{ request.GET.q}}{% endif %}" class="next">Вперед &rarr;</a>
        {% endif %}
    </span>
</div>
</div>  
</div> 
        </section>
        <!--/.BLOG END-->

        <!--CONTACT-->
        <section id="contact" class="white-bg">
          <div class="container">
            <div class="row">
              <div class="col-md-4">
                <h3 class="title-small">
                  <span>Контакты</span>
                </h3>
                <br>
                <p class="title-map">
                  Здесь вы можете оставить мне сообщение...
                </p>
                  <br>
                        <table class="w-content">
                          <tr>
                            <td class="title-map">Тел.:  </td>
                            <td class="break"> +38 (068) 235-13-73 </td>

                          </tr>
                          <tr>
                            <td class="title-map">Email: </td>
                            <td class="break"> denisenko.s.kr@gmail.com </td>
                          </tr>
                        </table>

              </div>
              <div class="col-md-4 col-md-offset-2 content-right">
                <form method="post" action="">{% csrf_token%}
                  <div class="group">
                    <input required="" name="name" type="text"><span class="highlight"></span><span class="bar"></span><label>Имя</label>
                  </div>
                  <div class="group">
                    <input required="" name="email" type="email"><span class="highlight"></span><span class="bar"></span><label>Email</label>
                  </div>
                  <div class="group">
                    <textarea required="" name="message" value=""></textarea><span class="highlight"></span><span class="bar"></span><label>Сообщение</label>
                  </div>
                  <input id="sendMessage"  type="submit" value="Отправить сообщение">
                </form>
              </div>
            </div>
          </div>
        </section>
        <!--/.CONTACT END-->

{% include "footer.html" %}
      <!--/.CONTENT END-->
      </div>
    <!--/.CONTENT-WRAP END-->
    </div>
{% endblock content%}

templates/preloader.html
{% load staticfiles %}  
 <!--PRELOADER   текст при загрузке(изменить картинку)!!!-->
    <div id="preloader">
      <div id="status">
        <img alt="logo" src="{% static 'images/200w.gif' %}">
      </div>
    </div>
    <!--/.PRELOADER END-->